(function (_ps) {
    "use strict";
    _ps.Math = (function () {
        var module = {};
        var abs = Math.abs;;
        var acos = Math.acos;;
        var asin = Math.asin;;
        var atan = Math.atan;;
        function atan2(y){  return function (x) {    return Math.atan2(y, x);  };};
        var ceil = Math.ceil;;
        var cos = Math.cos;;
        var exp = Math.exp;;
        var floor = Math.floor;;
        var log = Math.log;;
        function max(n1){  return function(n2) {    return Math.max(n1, n2);  }};
        function min(n1){  return function(n2) {    return Math.min(n1, n2);  }};
        function pow(n){  return function(p) {    return Math.pow(n, p);  }};
        var round = Math.round;;
        var sin = Math.sin;;
        var sqrt = Math.sqrt;;
        var tan = Math.tan;;
        var e       = Math.E;;
        var ln2     = Math.LN2;;
        var ln10    = Math.LN10;;
        var log2e   = Math.LOG2E;;
        var log10e  = Math.LOG10E;;
        var pi      = Math.PI;;
        var sqrt1_2 = Math.SQRT1_2;;
        var sqrt2   = Math.SQRT2;;
        module.sqrt2 = sqrt2;
        module.sqrt1_2 = sqrt1_2;
        module.pi = pi;
        module.log10e = log10e;
        module.log2e = log2e;
        module.ln10 = ln10;
        module.ln2 = ln2;
        module.e = e;
        module.tan = tan;
        module.sqrt = sqrt;
        module.sin = sin;
        module.round = round;
        module.pow = pow;
        module.min = min;
        module.max = max;
        module.log = log;
        module.floor = floor;
        module.exp = exp;
        module.cos = cos;
        module.ceil = ceil;
        module.atan2 = atan2;
        module.atan = atan;
        module.asin = asin;
        module.acos = acos;
        module.abs = abs;
        return module;
    })();
})((typeof module !== "undefined" && module.exports) ? module.exports : (typeof window !== "undefined") ? window.PS = window.PS || {} : (function () {
    throw "PureScript doesn't know how to export modules in the current environment";
})());